sudo: required

language: php
php:
  - '7.1'

notifications:
  email:
    recipients:
      - Ahmedkounasso@gmail.com
    on_success: always # default: change (other : never)
    on_failure: never # default: always

env:
  global:
    - NAME="Corese"
    - SOFTWARE_DESCRIBE="Corese"
    - VERSION="3.6.0"
#    - SPARQLSCORE_DATABASE="172.17.0.6" #local

services:
  - docker

before_install:
  - docker build -t corese .
#  - docker pull bordercloud/tft-jena-fuseki

script:
  - docker run -p 49160:8080 -d corese

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD ;
    docker push Ahmedko/corese;
    fi
